import { useState } from 'react';
import { ArrowDown, ArrowUp, Layers3, Pencil, Plus, Trash2 } from 'lucide-react';
import { EditorPopup } from './EditorPopup';
import { OrganizationTree } from './OrganizationTree';
import type { OrganizationView } from './ViewToggle';
import type { OrganizationNode } from '../../shared/organization-tree.mjs';
import type { Language } from '../lib/types';
type Sector = { id: string; name: string };
export function SectorsEditor({ sectors, onChange, language, view, projectName, disabled = false, onRemove, tree, onEditMember }: { sectors: Sector[]; onChange: (sectors: Sector[]) => void; language: Language; view: OrganizationView; projectName: string; disabled?: boolean; onRemove?: (id: string) => void; tree?: OrganizationNode; onEditMember?: (id: string) => void }) {
  const pt = language === 'pt', [editing, setEditing] = useState<Sector | null>(null), [name, setName] = useState('');
  function edit(sector: Sector) { setEditing(sector); setName(sector.name); }
  function save() { if (!name.trim() || !editing) return; const next = { ...editing, name: name.trim() }; onChange(sectors.some(s => s.id === next.id) ? sectors.map(s => s.id === next.id ? next : s) : [...sectors, next]); setEditing(null); }
  function remove(id: string) { if (onRemove) onRemove(id); else onChange(sectors.filter(s => s.id !== id)); }
  function move(index: number, delta: number) { const next = [...sectors], [item] = next.splice(index, 1); next.splice(index + delta, 0, item); onChange(next); }
  return <div className="sectors-editor">
    {view === 'hierarchy' ? <OrganizationTree editableSectorIds={disabled ? [] : sectors.map(s => s.id)} language={language} view={view} tree={tree || { id: 'preview', name: projectName || (pt ? 'Seu projeto' : 'Your project'), kind: 'project', children: sectors.map(s => ({ ...s, kind: 'sector', children: [] })) }} onEdit={node => { if (node.memberId) { onEditMember?.(node.memberId); return; } if (disabled) return; const sector = sectors.find(s => s.id === node.id); if (sector) edit(sector); }} /> : <div className="sector-rows">{sectors.map((sector, index) => <article className="sector-row" key={sector.id}><span className="sector-symbol"><Layers3 size={17} /></span><span className="sector-row-name">{sector.name}</span><div className="sector-row-actions"><button type="button" aria-label={`${pt ? 'Editar' : 'Edit'} ${sector.name}`} disabled={disabled} onClick={() => edit(sector)}><Pencil size={15} /></button><button type="button" aria-label={`${pt ? 'Mover acima' : 'Move up'} ${sector.name}`} disabled={disabled || index === 0} onClick={() => move(index, -1)}><ArrowUp size={15} /></button><button type="button" aria-label={`${pt ? 'Mover abaixo' : 'Move down'} ${sector.name}`} disabled={disabled || index === sectors.length - 1} onClick={() => move(index, 1)}><ArrowDown size={15} /></button><button className="danger" type="button" aria-label={`${pt ? 'Remover' : 'Remove'} ${sector.name}`} disabled={disabled} onClick={() => remove(sector.id)}><Trash2 size={15} /></button></div></article>)}{!sectors.length && <p className="workspace-empty">{pt ? 'Adicione os setores da sua equipe.' : 'Add your team’s sectors.'}</p>}</div>}
    <button className="add-sector" type="button" disabled={disabled || sectors.length >= 100} onClick={() => edit({ id: crypto.randomUUID(), name: '' })}><Plus size={16} />{pt ? 'Adicionar setor' : 'Add sector'}</button>
    {editing && <EditorPopup title={pt ? 'Editar setor' : 'Edit sector'} closeLabel={pt ? 'Fechar' : 'Close'} onClose={() => setEditing(null)}><div className="editor-popup-body"><label className="workspace-field"><span>{pt ? 'Nome do setor' : 'Sector name'}</span><input autoFocus required maxLength={100} value={name} onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); save(); } }} /></label></div><footer>{sectors.some(s => s.id === editing.id) && <button className="danger" type="button" onClick={() => { remove(editing.id); setEditing(null); }}><Trash2 size={15} />{pt ? 'Remover' : 'Remove'}</button>}<button className="primary" type="button" disabled={!name.trim()} onClick={save}>{pt ? 'Aplicar' : 'Apply'}</button></footer></EditorPopup>}
  </div>;
}
