import { useEffect, useState } from 'react';
import { useAuth } from '../lib/auth';
import type { Language } from '../lib/types';
type Insights = { notice: string; visits: { total: number; unique: number; days: { date: string; visits: number; unique: number }[] }; members: { memberId: string; name: string; lastSeenAt: string | null; lastProjectActivity: string | null; activeDays: number; accesses: number; artifactCreated: number; artifactEdited: number; recent: { date: string; projectName: string; artifactCreated: number; artifactEdited: number; organizationUpdated: number }[] }[] };
export function TeamInsights({ teamId, language }: { teamId: string; language: Language }) {
  const { api } = useAuth(), pt = language === 'pt';
  const [data, setData] = useState<Insights | null>(null), [error, setError] = useState('');
  useEffect(() => { let active = true; void api<Insights>(`/teams/${teamId}/insights`).then(r => { if (active) setData(r); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [api, teamId]);
  if (!data) return <p role="status">{error || (pt ? 'Carregando estatísticas…' : 'Loading insights…')}</p>;
  const max = Math.max(1, ...data.visits.days.map(d => d.visits));
  const date = (value: string | null) => value ? new Date(value).toLocaleString(pt ? 'pt-BR' : 'en-GB') : '—';
  return <section className="organization-panel team-insights"><h3>{pt ? 'Visitas e participação' : 'Visits and participation'}</h3><p>{data.notice}</p><div className="insight-totals"><span><strong>{data.visits.total}</strong>{pt ? 'visitas desde a ativação' : 'visits since activation'}</span><span><strong>{data.visits.unique}</strong>{pt ? 'visitantes únicos em 30 dias' : 'unique visitors in 30 days'}</span></div><p>{pt ? 'Apenas contas autenticadas de fora da equipe. Reaberturas em até 30 minutos contam como uma visita. Dias em UTC.' : 'Only authenticated visitors outside the team. Reopening within 30 minutes counts as one visit. UTC days.'}</p>
    <div className="visits-chart" role="img" aria-label={pt ? 'Visitas por dia nos últimos 30 dias' : 'Daily visits in the last 30 days'}>{data.visits.days.map(d => <div key={d.date} title={`${d.date}: ${d.visits}`} style={{ height: `${Math.max(2, d.visits / max * 100)}%` }} />)}</div><details><summary>{pt ? 'Ver dados do gráfico' : 'Chart data'}</summary><div className="activity-scroll"><table><thead><tr><th>{pt ? 'Dia' : 'Day'}</th><th>{pt ? 'Visitas' : 'Visits'}</th><th>{pt ? 'Visitantes únicos' : 'Unique visitors'}</th></tr></thead><tbody>{data.visits.days.map(d => <tr key={d.date}><td>{d.date}</td><td>{d.visits}</td><td>{d.unique}</td></tr>)}</tbody></table></div></details>
    <h4>{pt ? 'Atividade dos membros · últimos 30 dias' : 'Member activity · last 30 days'}</h4><div className="activity-scroll"><table><thead><tr>{(pt ? ['Pessoa', 'Último acesso', 'Última atividade no projeto', 'Dias ativos', 'Acessos aos projetos', 'Artefatos criados', 'Edições de artefatos'] : ['Person', 'Last seen', 'Last project activity', 'Active days', 'Project visits', 'Artifacts created', 'Artifact edits']).map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{data.members.map(m => <tr key={m.memberId}><td>{m.name}</td><td>{date(m.lastSeenAt)}</td><td>{date(m.lastProjectActivity)}</td><td>{m.activeDays}</td><td>{m.accesses}</td><td>{m.artifactCreated}</td><td>{m.artifactEdited}</td></tr>)}</tbody></table></div>
    <details><summary>{pt ? 'Resumo das alterações recentes' : 'Recent changes summary'}</summary>{data.members.flatMap(m => m.recent.filter(r => r.artifactCreated || r.artifactEdited || r.organizationUpdated).map(r => <p key={`${m.memberId}:${r.date}:${r.projectName}`}>{r.date} · {m.name} · {r.projectName}: {r.artifactCreated} {pt ? 'artefatos criados' : 'artifacts created'}, {r.artifactEdited} {pt ? 'edições' : 'edits'}, {r.organizationUpdated} {pt ? 'alterações da organização' : 'organization changes'}.</p>))}</details>
  </section>;
}
