/* global document, window */
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
import { buildApp } from "../server/app.mjs";
import { createEngineeringValidationModel, validationMemoryText } from "../examples/engineering-validation.mjs";

// Real React + authenticated API + persistence; only the external extraction provider is mocked.
// Uses an isolated temporary store and test browser. Never modifies the user's database.
const directory = await mkdtemp(join(tmpdir(), "norte-browser-"));
const port = Number(process.env.NORTE_VISUAL_PORT || 5275);
const baseUrl = `http://127.0.0.1:${port}/norte/`;
let generations = 0, failGeneration = true, artifactId = "";
const app = await buildApp({ storeFile: join(directory, "state.json"), logger: false, systemAi: { apiKey: "test-provider", fetch: async (_url, options) => {
  if (JSON.parse(options.body).contents[0].parts[0].text.startsWith("Give concise")) return new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: '{"inferences":[]}' }] } }] }), { status: 200 });
  generations += 1;
  if (failGeneration) return new Response("{}", { status: 503 });
  const model = createEngineeringValidationModel();
  model.evidence = model.evidence.map((item) => ({ ...item, artifactId }));
  return new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(model) }] } }] }), { status: 200 });
} } });
const registration = await app.inject({ method: "POST", url: "/api/auth/register", payload: { name: "Validation Engineer", email: "validation@example.test", password: "Engineering validation passphrase 42" } });
assert.equal(registration.statusCode, 201, registration.body);
const session = registration.json();
const cookie = registration.headers["set-cookie"].split(";")[0];
const headers = { cookie, "x-csrf-token": session.csrfToken };
const request = async (method, url, payload) => {
  const response = await app.inject({ method, url, payload, headers });
  assert.ok(response.statusCode < 400, `${url}: ${response.body}`);
  return response.statusCode === 204 ? undefined : response.json();
};
const initial = await request("GET", "/api/projects");
assert.equal(initial.projects.length, 1);
const projectId = initial.projects[0].id;
let project = (await request("GET", `/api/projects/${projectId}`)).project;
project.context.assignments = [{ memberId: session.user.memberId, roleId: "captain", sectorId: "" }];
project.context.configured = true;
const artifact = (await request("POST", "/api/artifacts", { kind: "document", label: "Validation memory", description: "Explicit test fixture", url: `data:text/plain;base64,${Buffer.from(validationMemoryText).toString("base64")}`, scope: "project", ownerId: projectId, tags: [], fileName: "validation.txt", mimeType: "text/plain", size: Buffer.byteLength(validationMemoryText) })).artifact;
artifactId = artifact.id;
project.context.projectArtifactIds = [artifact.id];
await request("PUT", `/api/projects/${projectId}`, project);
const vite = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", String(port), "--strictPort"], { env: { ...process.env, VITE_DEMO_MODE: "false" }, stdio: ["ignore", "pipe", "pipe"] });
const viteReady = new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error("Vite startup timeout")), 15000); vite.stdout.on("data", (chunk) => { if (String(chunk).includes("Local:")) { clearTimeout(timer); resolve(); } }); vite.once("exit", (code) => reject(new Error(`Vite exited ${code}`))); });
const browser = await chromium.launch({ executablePath: process.env.NORTE_CHROME || "/opt/google/chrome/chrome", headless: true, args: ["--no-sandbox"] });
const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
const split = cookie.indexOf("=");
await context.addCookies([{ name: cookie.slice(0, split), value: cookie.slice(split + 1), url: new URL(baseUrl).origin }]);
const errors = [];
const page = await context.newPage();
page.on("pageerror", (error) => errors.push(error.message));
await context.route("**/api/**", async (route) => {
  const incoming = route.request();
  const response = await app.inject({ method: incoming.method(), url: new URL(incoming.url()).pathname + new URL(incoming.url()).search, headers: { ...await incoming.allHeaders(), host: `127.0.0.1:${port}` }, ...(incoming.postData() ? { payload: incoming.postData() } : {}) });
  const outputHeaders = Object.fromEntries(Object.entries(response.headers).filter(([name]) => !["content-length", "transfer-encoding", "connection", "set-cookie"].includes(name)).map(([name, value]) => [name, String(value)]));
  await route.fulfill({ status: response.statusCode, headers: outputHeaders, body: response.body });
});
const node = (id) => page.locator(`[data-entity-id="${id}"]`);
const closeDialog = () => page.getByRole("dialog").getByRole("button", { name: /^(Fechar|Close)$/u }).click();
const waitSaved = () => page.waitForTimeout(450);
const results = [];
try {
  await viteReady;
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  await page.locator(".home-action-card.accent-create").waitFor();
  console.log("Browser: authenticated home loaded");
  assert.ok(await page.locator(".home-action-card.accent-create").isDisabled());
  await page.locator(".home-action-card.accent-create").dispatchEvent("click");
  await page.locator(".home-action-card.accent-create").dispatchEvent("keydown", { key: "Enter" });
  assert.ok(page.url().endsWith("/norte/"));
  await page.locator(".mission-sidebar-toggle").click();
  assert.equal(await page.locator(".mission-context-switcher select").count(), 1);
  assert.equal(await page.locator(".mission-project-team strong").innerText(), "Norte Validation Team");
  assert.ok(await page.locator(".mission-phase").nth(1).isDisabled());
  await page.locator(".home-action-card.accent-team").click();
  const createTeam = page.locator(".teams-hub-heading > button");
  assert.ok(await createTeam.isDisabled());
  await createTeam.dispatchEvent("click");
  await createTeam.dispatchEvent("keydown", { key: " " });
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  await page.locator(".home-action-card.accent-open").click();
  await page.locator(".home-project-open").click();
  await page.locator(".pm-footer > button").click();
  await page.locator(".pm-feedback").waitFor();
  assert.ok((await page.locator(".pm-feedback").innerText()).includes("temporariamente indisponível"));
  assert.equal((await request("GET", `/api/projects/${projectId}`)).project.engineeringSystem, undefined);
  assert.ok(page.url().includes("study-setup"));
  failGeneration = false;
  await page.locator(".pm-footer > button").click();
  await page.locator(".engineering-graph").waitFor();
  assert.equal(generations, 2);
  assert.equal(await page.getByRole("tab", { selected: true }).innerText(), "Sistema");
  assert.equal(await page.getByRole("button", { name: /Gerar arquitetura|Generate initial/u }).count(), 0);
  const baseline = (await request("GET", `/api/projects/${projectId}`)).project;
  assert.ok(baseline.engineeringSystem);
  assert.equal(baseline.phaseProgress.highestUnlockedStep, 1);
  assert.equal(await page.locator(".engineering-node").count(), 6);
  assert.equal(await page.locator('[data-entity-id^="REQ-"]').count(), 0);
  await page.locator(".mission-phase").first().click();
  await page.locator(".pm-workspace").waitFor();
  assert.equal(await page.locator(".mission-phase").nth(1).isDisabled(), false);
  await page.reload({ waitUntil: "networkidle" });
  assert.equal(await page.locator(".mission-phase").nth(1).isDisabled(), false);
  await page.locator(".mission-phase").nth(1).click();
  await page.locator(".engineering-graph").waitFor();
  assert.equal(generations, 2);
  await page.locator(".mission-sidebar-toggle").click();
  await page.waitForTimeout(220);
  await page.screenshot({ path: "/tmp/norte-system-macro.png", fullPage: true });
  await node("communication").locator(".engineering-node-main").click();
  await node("radio").waitFor();
  await node("radio").locator(".engineering-node-main").click();
  assert.equal(await page.getByRole("dialog").count(), 0);
  const graphWidth = await page.locator(".engineering-graph").evaluate((element) => element.clientWidth);
  await node("radio").locator(".engineering-node-info").click();
  await page.getByRole("dialog").waitFor();
  await page.getByRole("dialog").locator(".engineering-evidence summary").first().click();
  assert.ok((await page.getByRole("dialog").innerText()).includes("400 mA"));
  await closeDialog();
  assert.equal(await page.locator(".engineering-graph").evaluate((element) => element.clientWidth), graphWidth);
  await node("radio").getByRole("button", { name: "E se…", exact: true }).click();
  await page.getByLabel("Novo valor", { exact: true }).fill("1.2");
  await page.getByLabel("Unidade", { exact: true }).fill("A");
  await page.getByRole("button", { name: "Ver consequências" }).click();
  await page.locator(".engineering-scenario").waitFor();
  assert.ok((await node("regulator").getAttribute("class")).includes("status-critical"));
  assert.ok((await node("regulator").innerText()).includes("1.2 A > 0.8 A"));
  await node("regulator").locator(".engineering-node-info").click();
  assert.ok((await page.getByRole("dialog").innerText()).includes("1.2 A > 0.8 A"));
  await page.getByRole("dialog").getByRole("button", { name: "Fechar", exact: true }).focus();
  await page.keyboard.press("Tab");
  assert.equal(await page.evaluate(() => document.activeElement.tagName), "SUMMARY");
  await page.keyboard.press("Enter");
  assert.ok(await page.getByRole("dialog").locator("details[open]").count());
  await page.keyboard.press("Escape");
  assert.equal(await node("regulator").locator(".engineering-node-info").evaluate((element) => document.activeElement === element), true);
  await page.screenshot({ path: "/tmp/norte-impact-current.png", fullPage: true });
  await page.getByRole("button", { name: "EN", exact: true }).click();
  await page.getByRole("button", { name: "Save scenario", exact: true }).waitFor();
  await page.screenshot({ path: "/tmp/norte-impact-current-en.png", fullPage: true });
  await page.getByRole("button", { name: "PT", exact: true }).click();
  await page.getByRole("button", { name: "Salvar cenário" }).click();
  await waitSaved();
  assert.equal((await request("GET", `/api/projects/${projectId}`)).project.engineeringSystem.scenarios.length, 1);
  assert.deepEqual((await request("GET", `/api/projects/${projectId}`)).project.engineeringSystem.entities, baseline.engineeringSystem.entities);
  await page.getByRole("button", { name: "Limpar análise" }).click();
  await page.locator(".engineering-requirements-trigger").click();
  assert.equal(await page.locator(".engineering-requirement-row").count(), 2);
  await page.getByLabel("Buscar requisitos").fill("mass");
  assert.equal(await page.locator(".engineering-requirement-row").count(), 1);
  await page.getByLabel("Buscar requisitos").fill("");
  await page.getByRole("button", { name: "Filtrar", exact: true }).click();
  await page.locator(".engineering-requirement-facets select").first().selectOption("Power");
  assert.equal(await page.locator(".engineering-requirement-row").count(), 1);
  await page.getByRole("button", { name: "Limpar filtros" }).click();
  assert.equal(await page.locator(".engineering-requirement-row").count(), 2);
  await page.locator(".engineering-requirement-row").first().locator("button").last().click();
  await page.getByRole("button", { name: "Corrigir", exact: true }).click();
  await page.getByLabel("Enunciado revisado").fill("Autonomy ≥ 90 min, reviewed by the team");
  await page.getByLabel("Revisões (separadas por vírgula)").fill("PDR");
  await page.getByRole("button", { name: "Salvar correção" }).click();
  await waitSaved();
  const revised = (await request("GET", `/api/projects/${projectId}`)).project.engineeringSystem.requirements.find((item) => item.id === "REQ-07");
  assert.equal(revised.statement, "Autonomy ≥ 90 min, reviewed by the team");
  assert.equal(revised.originalStatement, "Autonomy ≥ 90 min");
  assert.deepEqual(revised.originalSourceRefs, ["req-duration"]);
  assert.deepEqual(revised.reviewTags, ["PDR"]);
  await closeDialog();
  await page.locator(".engineering-requirements-trigger").click();
  // Requirements list is independent of graph selection and is dismissed by trace.
  await page.locator(".engineering-requirement-row").first().locator("button").first().click();
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.locator(".engineering-trace-bar").waitFor();
  await page.getByRole("tab", { name: /Descoberta/u }).click();
  await page.locator(".lab-canvas").waitFor();
  for (const removed of ["Arrumar mapa", "Estruturar missão", "Organização automática"]) assert.equal(await page.getByRole("button", { name: removed, exact: true }).count(), 0);
  await page.getByRole("button", { name: "Nova ideia", exact: true }).first().click();
  await page.locator(".lab-composer textarea").fill("Payload 280 g");
  await page.locator(".lab-composer textarea").press("Enter");
  await page.locator(".lab-composer textarea").press("Escape");
  await page.locator(".lab-node").getByRole("button", { name: "Ver impacto" }).click();
  await page.locator(".engineering-scenario").waitFor();
  assert.equal(await page.getByRole("dialog").count(), 0);
  assert.ok((await node("payload").innerText()).includes("280"));
  assert.equal(await node("radio").count(), 0);
  assert.ok((await page.locator(".engineering-requirement-impact").innerText()).includes("Conflito"));
  await page.screenshot({ path: "/tmp/norte-discovery-impact.png", fullPage: true });
  await page.getByRole("button", { name: "Limpar análise" }).click();
  assert.equal(await page.locator(".lab-node").count(), 1);
  await page.getByRole("button", { name: "Desfazer", exact: true }).click();
  assert.equal(await page.locator(".lab-node").count(), 0);
  await page.getByRole("button", { name: "Refazer", exact: true }).click();
  assert.equal(await page.locator(".lab-node").count(), 1);
  await waitSaved();
  await page.reload({ waitUntil: "networkidle" });
  await page.locator(".lab-node").waitFor();
  assert.equal(generations, 2);
  // Each selected project brings its own progress, team and workspace.
  const secondTeam = (await request("POST", "/api/teams", { name: "Independent test team", description: "Temporary acceptance fixture" })).team;
  const secondProject = { ...project, id: "independent-browser-project", name: "Independent project", phaseProgress: { highestUnlockedStep: 0 }, navigation: { lastRoute: "setup" }, context: { ...project.context, teamId: secondTeam.id, teamName: secondTeam.name, projectArtifactIds: [] } };
  await request("POST", "/api/projects", secondProject);
  await page.reload({ waitUntil: "networkidle" });
  await page.locator(".mission-sidebar-toggle").click();
  await page.locator(".mission-context-switcher select").selectOption(secondProject.id);
  await page.locator(".pm-workspace").waitFor();
  assert.ok(await page.locator(".mission-phase").nth(1).isDisabled());
  assert.equal(await page.locator(".mission-project-team strong").innerText(), secondTeam.name);
  await page.locator(".mission-context-switcher select").selectOption(projectId);
  await page.locator(".lab-canvas").waitFor();
  // The current phase is aria-disabled because it is already selected, but remains unlocked.
  assert.equal(await page.locator(".mission-phase").nth(1).getAttribute("disabled"), null);
  assert.equal(await page.locator(".mission-phase").nth(1).getAttribute("aria-current"), "step");
  assert.equal(await page.locator(".mission-project-team strong").innerText(), "Norte Validation Team");
  await page.locator(".mission-sidebar-toggle").click();
  await page.getByRole("tab", { name: /Cronograma/u }).click();
  await page.locator(".conception-timeline").waitFor();
  for (const [width, height] of [[1366, 768], [390, 844]]) {
    await page.setViewportSize({ width, height });
    await page.getByRole("tab", { name: "Sistema", exact: true }).click();
    await page.locator(".engineering-graph").waitFor();
    assert.ok(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth + 1), `Horizontal overflow at ${width}`);
    await page.screenshot({ path: `/tmp/norte-system-${width}.png`, fullPage: true });
    results.push({ width, height, overflow: false });
  }
  await request("DELETE", `/api/projects/${projectId}`);
  await request("DELETE", "/api/projects/independent-browser-project");
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  await page.locator(".home-action-card.accent-open").click();
  assert.ok(await page.locator(".home-project-dialog-empty button").isDisabled());
  await page.locator(".home-project-dialog-empty button").dispatchEvent("click");
  await page.locator(".home-project-dialog-empty button").dispatchEvent("keydown", { key: "Enter" });
  assert.equal(await page.locator(".pm-workspace").count(), 0);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, generations, checks: ["disabled creation", "owning team", "persistent phases", "automatic initialization and recovery", "macro and drilldown", "contextual details", "provenance", "current conflict", "scenario save", "requirement filtering/editing/source preservation", "requirement trace", "project-specific progress and team switching", "Discovery mass conflict", "undo redo persistence", "timeline", "responsive"], viewports: results }, null, 2));
} catch (error) { await page.screenshot({ path: "/tmp/norte-browser-failure.png", fullPage: true }).catch(() => undefined); throw error; }
finally { await browser.close(); await app.close(); vite.kill("SIGTERM"); await rm(directory, { recursive: true, force: true }); }
