import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
import { buildApp } from "../server/app.mjs";
import { createQuetzalDesignModel } from "../benchmark/quetzal1/context/design-context.mjs";

// Browser friction measurement with real project/API persistence and explicit provider fixture.
// This is an interface test, never a claim of live extraction accuracy or student outcomes.
const directory = await mkdtemp(join(tmpdir(), "norte-quetzal-browser-"));
const port = Number(process.env.NORTE_VISUAL_PORT || 5277);
const base = `http://127.0.0.1:${port}/norte/`;
let generations = 0, vite, browser;
const app = await buildApp({ storeFile: join(directory, "state.json"), logger: false, systemAi: { apiKey: "test-provider", fetch: async (_url, options) => {
  const payload = JSON.parse(options.body);
  assert.ok(payload.contents[0].parts[0].text.includes("transmit input power 2640 mW"));
  assert.ok(!options.body.includes("QUETZAL_EVALUATOR_ONLY"));
  generations += 1;
  return new Response(JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(createQuetzalDesignModel()) }] } }] }), { status: 200 });
} } });
try {
  const registration = await app.inject({ method: "POST", url: "/api/auth/register", payload: { name: "Validation Engineer", email: "quetzal-validation@example.test", password: "Quetzal validation passphrase 42" } });
  assert.equal(registration.statusCode, 201);
  const session = registration.json(), cookie = registration.headers["set-cookie"].split(";")[0];
  const headers = { cookie, "x-csrf-token": session.csrfToken };
  const projectId = (await app.inject({ method: "GET", url: "/api/projects", headers })).json().projects[0].id;
  const saved = async () => (await app.inject({ method: "GET", url: `/api/projects/${projectId}`, headers })).json().project;
  assert.equal((await saved()).context.programId, null);
  assert.equal((await saved()).context.projectArtifactIds.length, 2);
  assert.equal((await saved()).engineeringSystem, undefined);
  vite = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", String(port), "--strictPort"], { env: { ...process.env, VITE_DEMO_MODE: "false" }, stdio: ["ignore", "pipe", "pipe"] });
  await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error("Vite startup timeout")), 15000); vite.stdout.on("data", (chunk) => { if (String(chunk).includes("Local:")) { clearTimeout(timer); resolve(); } }); vite.once("exit", (code) => reject(new Error(`Vite exited ${code}`))); });
  browser = await chromium.launch({ executablePath: process.env.NORTE_CHROME || "/opt/google/chrome/chrome", headless: true, args: ["--no-sandbox"] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, acceptDownloads: true });
  const split = cookie.indexOf("=");
  await context.addCookies([{ name: cookie.slice(0, split), value: cookie.slice(split + 1), url: new URL(base).origin }]);
  await context.route("**/api/**", async (route) => {
    const request = route.request();
    const response = await app.inject({ method: request.method(), url: new URL(request.url()).pathname + new URL(request.url()).search, headers: { ...await request.allHeaders(), host: `127.0.0.1:${port}` }, ...(request.postData() ? { payload: request.postData() } : {}) });
    const outputHeaders = Object.fromEntries(Object.entries(response.headers).filter(([name]) => !["content-length", "transfer-encoding", "connection", "set-cookie"].includes(name)).map(([name, value]) => [name, String(value)]));
    await route.fulfill({ status: response.statusCode, headers: outputHeaders, body: response.body });
  });
  const page = await context.newPage(), errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const node = (id) => page.locator(`[data-entity-id="${id}"]`);
  await page.goto(base, { waitUntil: "networkidle" });
  await page.locator(".home-action-card.accent-open").click();
  await page.locator(".home-project-open").click();
  await page.locator(".pm-workspace").waitFor();
  const initializationStart = performance.now();
  await page.locator(".pm-footer > button").click();
  await page.locator(".engineering-graph").waitFor();
  const initializationMs = performance.now() - initializationStart;
  assert.equal(generations, 1);
  assert.equal((await saved()).phaseProgress.highestUnlockedStep, 1);
  assert.equal((await saved()).engineeringSystem.entities.length, 18);
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.screenshot({ path: "/tmp/norte-quetzal-system.png", fullPage: true });
  await page.getByRole("tab", { name: /Descoberta/u }).click();
  await page.locator(".lab-canvas").waitFor();
  await page.getByRole("button", { name: "Nova ideia", exact: true }).first().click();
  await page.locator(".lab-composer textarea").fill("AX100 TX de 3,6% para 10%");
  await page.locator(".lab-composer textarea").press("Enter");
  const impactStart = performance.now();
  await page.locator(".lab-node").getByRole("button", { name: "Ver impacto" }).click();
  await page.locator(".engineering-scenario").waitFor();
  const impactMs = performance.now() - impactStart;
  assert.equal(await page.getByRole("dialog").count(), 0);
  assert.ok((await node("energy-balance").getAttribute("class")).includes("status-valid"));
  assert.equal(await page.locator(".engineering-node.status-critical").count(), 0);
  assert.ok((await node("comms-average").locator(".engineering-node-values").innerText()).includes("0.4719 W"));
  assert.ok((await node("power-budget").locator(".engineering-node-values").innerText()).includes("1.1662 W"));
  await page.keyboard.press("Tab");
  await node("energy-balance").locator(".engineering-node-info").focus();
  await node("energy-balance").locator(".engineering-node-info").click();
  assert.ok((await page.getByRole("dialog").innerText()).includes("1.58"));
  await page.getByRole("dialog").locator(".engineering-evidence summary:visible").first().click();
  await page.getByRole("dialog").locator(".engineering-source:visible").first().waitFor();
  await page.getByRole("dialog").getByRole("link", { name: "Abrir fonte" }).first().waitFor();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Limpar análise" }).click();
  await page.locator(".lab-node-head button").click();
  await page.locator(".lab-composer textarea").fill("AX100 transmitter remains continuously active");
  await page.locator(".lab-composer textarea").press("Enter");
  await page.locator(".lab-node").getByRole("button", { name: "Ver impacto" }).click();
  await page.locator(".engineering-scenario").waitFor();
  assert.ok((await node("energy-balance").getAttribute("class")).includes("status-review"));
  assert.ok((await node("battery").getAttribute("class")).includes("status-review"));
  assert.ok((await node("comms-average").locator(".engineering-node-values").innerText()).includes("2.64 W"));
  assert.ok((await node("power-budget").locator(".engineering-node-values").innerText()).includes("3.5511 W"));
  assert.ok((await node("energy-balance").locator(".engineering-node-values").innerText()).includes("-1.9711 W"));
  assert.ok((await page.locator(".engineering-requirement-impact").first().getAttribute("class")).includes("status-critical"));
  assert.ok((await page.locator(".engineering-requirement-impact.status-critical").innerText()).includes("Conflito"));
  await page.getByRole("button", { name: "EN", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1200 });
  await page.screenshot({ path: "/tmp/norte-quetzal-impact.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.getByRole("button", { name: "Save scenario", exact: true }).click();
  await page.waitForTimeout(450);
  const persisted = await saved();
  assert.equal(persisted.engineeringSystem.entities.find((entity) => entity.id === "radio").properties.find((property) => property.key === "tx_duty_cycle").value, 3.6);
  assert.equal(persisted.engineeringSystem.scenarios[0].change.newValues[0].value, 100);
  await page.reload({ waitUntil: "networkidle" });
  await page.locator(".lab-node").waitFor();
  assert.equal(generations, 1);
  assert.deepEqual(errors, []);
  const report = { passed: true, provider: "explicit fixture; live extraction measured separately", initializationMs, impactMs, actionsFromTypedHypothesisToImpact: 2, actionSequence: ["Submit typed hypothesis", "See impact"], actionsFromSavedHypothesisToImpact: 1, configurationStepsAfterMemory: 0, generations, checks: ["seeded design memory", "no reference program", "automatic system", "duty 10% has positive margin", "continuous TX deficit", "accessible evidence", "baseline preserved", "scenario persistence"] };
  await mkdir("var/benchmarks", { recursive: true });
  await writeFile("var/benchmarks/quetzal-friction.json", JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser?.close(); vite?.kill("SIGTERM"); await app.close(); await rm(directory, { recursive: true, force: true }); }
